#!/usr/bin/env node
// publish.js — publish the merged word bank into the @sabd/wordbank package.
//
// Usage: node src/publish.js [--version=1.0.0] [--scale=legacy|unified]
//
// Reads   data/clean/sabd-wordbank.json   (produced by merge.js)
//         data/clean/stats.json
// Writes  ../../packages/wordbank/data/sabd-wordbank.json      (JSON artifact)
//         ../../packages/wordbank/data/wordbank.meta.json      (version + counts)
//         ../../packages/wordbank/src/generated/word-bank.generated.ts
//                                                 (portable typed module — RN/node/web)
//
// Phase 4 (`--scale=unified`): reads from data/clean/unified/ and writes the PARALLEL
// unified artifact set (sabd-wordbank-unified.json, wordbank-unified.meta.json,
// word-bank-unified.generated.ts) with a `scale` marker (edge-case F5: a bank is
// self-describing, so a cached copy can never be mis-banded). The legacy artifacts —
// what the app actually serves under engine config 2.0.0 — are untouched until the
// gated 3.0.0 flip (F7).
//
// The version stamp is the `--version` arg, else the existing meta version, else 0.1.0.
// Dependency-free on purpose (no @sabd/contracts import) so it runs in a bare node.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CLEAN_DIR = path.join(ROOT, 'data', 'clean');
const WORDBANK_PKG = path.resolve(ROOT, '..', '..', 'packages', 'wordbank');
const WB_DATA = path.join(WORDBANK_PKG, 'data');
const WB_GENERATED = path.join(WORDBANK_PKG, 'src', 'generated');

function arg(name) {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.split('=').slice(1).join('=') : undefined;
}

// Per-scale publish targets. Suffixed filenames keep the two banks side by side in
// @sabd/wordbank; `scale` is stamped into the meta + generated module (F5).
const TARGETS = {
  legacy: {
    scale: 'elo-legacy',
    cleanSubdir: '',
    bankFile: 'sabd-wordbank.json',
    metaFile: 'wordbank.meta.json',
    generatedFile: 'word-bank.generated.ts',
    exportPrefix: 'WORD_BANK',
  },
  unified: {
    scale: 'unified',
    cleanSubdir: 'unified',
    bankFile: 'sabd-wordbank-unified.json',
    metaFile: 'wordbank-unified.meta.json',
    generatedFile: 'word-bank-unified.generated.ts',
    exportPrefix: 'UNIFIED_WORD_BANK',
  },
};

const scaleArg = arg('scale') ?? 'legacy';
const TARGET = TARGETS[scaleArg];
if (!TARGET) {
  console.error(`Unknown --scale=${scaleArg} (expected ${Object.keys(TARGETS).join('|')})`);
  process.exit(2);
}

function readJson(p, fallback) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return fallback;
  }
}

function resolveVersion() {
  const cli = arg('version');
  if (cli) return cli;
  const existing = readJson(path.join(WB_DATA, TARGET.metaFile), null);
  if (existing?.wordBankVersion) return existing.wordBankVersion;
  return '0.1.0';
}

function main() {
  const cleanDir = path.join(CLEAN_DIR, TARGET.cleanSubdir);
  const bankPath = path.join(cleanDir, 'sabd-wordbank.json');
  const bank = readJson(bankPath, null);
  if (!Array.isArray(bank)) {
    console.error(`No merged bank at ${bankPath} — run \`merge\` first.`);
    process.exit(1);
  }
  const stats = readJson(path.join(cleanDir, 'stats.json'), { topics: {} });
  const version = resolveVersion();
  // generatedAt comes from the merge stats (a build artifact), not wall-clock here.
  const generatedAt = stats.generatedAt ?? null;

  const topicCounts = {};
  for (const e of bank) topicCounts[e.topic] = (topicCounts[e.topic] ?? 0) + 1;

  const meta = {
    wordBankVersion: version,
    scale: TARGET.scale,
    generatedAt,
    count: bank.length,
    topics: topicCounts,
  };

  fs.mkdirSync(WB_DATA, { recursive: true });
  fs.mkdirSync(WB_GENERATED, { recursive: true });

  fs.writeFileSync(path.join(WB_DATA, TARGET.bankFile), JSON.stringify(bank, null, 2) + '\n');
  fs.writeFileSync(path.join(WB_DATA, TARGET.metaFile), JSON.stringify(meta, null, 2) + '\n');

  const P = TARGET.exportPrefix;
  const generated =
    `// GENERATED by tools/content-pipeline/src/publish.js — DO NOT EDIT BY HAND.\n` +
    `// Source: data/clean/${TARGET.cleanSubdir ? TARGET.cleanSubdir + '/' : ''}sabd-wordbank.json` +
    `  ·  wordBankVersion ${version}  ·  scale ${TARGET.scale}\n` +
    `import type { WordEntry } from '@sabd/contracts';\n\n` +
    `export const ${P}_VERSION = ${JSON.stringify(version)};\n` +
    `export const ${P}_SCALE = ${JSON.stringify(TARGET.scale)};\n` +
    `export const ${P}_GENERATED_AT = ${JSON.stringify(generatedAt)};\n\n` +
    `export const ${P}: readonly WordEntry[] = ${JSON.stringify(bank, null, 2)};\n`;
  fs.writeFileSync(path.join(WB_GENERATED, TARGET.generatedFile), generated);

  console.log(
    `Published ${scaleArg} word bank v${version} (${TARGET.scale}): ${bank.length} entries → packages/wordbank`,
  );
  for (const [topic, n] of Object.entries(topicCounts)) console.log(`  ${topic}: ${n}`);
}

main();
