#!/usr/bin/env node
// publish.js — publish the merged word bank into the @sabd/wordbank package.
//
// Usage: node src/publish.js [--version=1.0.0]
//
// Reads   data/clean/sabd-wordbank.json   (produced by merge.js)
//         data/clean/stats.json
// Writes  ../../packages/wordbank/data/sabd-wordbank.json      (JSON artifact)
//         ../../packages/wordbank/data/wordbank.meta.json      (version + counts)
//         ../../packages/wordbank/src/generated/word-bank.generated.ts
//                                                 (portable typed module — RN/node/web)
//
// The version stamp is the `--version` arg, else the existing meta version, else 0.1.0.
// Dependency-free on purpose (no @sabd/contracts import) so it runs in a bare node.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CLEAN_DIR = path.join(ROOT, 'data', 'clean');
const WORDBANK_PKG = path.resolve(ROOT, '..', '..', 'packages', 'wordbank');
const WB_DATA = path.join(WORDBANK_PKG, 'data');
const WB_GENERATED = path.join(WORDBANK_PKG, 'src', 'generated');

function arg(name) {
  const hit = process.argv.slice(2).find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.split('=').slice(1).join('=') : undefined;
}

function readJson(p, fallback) {
  try {
    return JSON.parse(fs.readFileSync(p, 'utf8'));
  } catch {
    return fallback;
  }
}

function resolveVersion() {
  const cli = arg('version');
  if (cli) return cli;
  const existing = readJson(path.join(WB_DATA, 'wordbank.meta.json'), null);
  if (existing?.wordBankVersion) return existing.wordBankVersion;
  return '0.1.0';
}

function main() {
  const bankPath = path.join(CLEAN_DIR, 'sabd-wordbank.json');
  const bank = readJson(bankPath, null);
  if (!Array.isArray(bank)) {
    console.error(`No merged bank at ${bankPath} — run \`merge\` first.`);
    process.exit(1);
  }
  const stats = readJson(path.join(CLEAN_DIR, 'stats.json'), { topics: {} });
  const version = resolveVersion();
  // generatedAt comes from the merge stats (a build artifact), not wall-clock here.
  const generatedAt = stats.generatedAt ?? null;

  const topicCounts = {};
  for (const e of bank) topicCounts[e.topic] = (topicCounts[e.topic] ?? 0) + 1;

  const meta = {
    wordBankVersion: version,
    generatedAt,
    count: bank.length,
    topics: topicCounts,
  };

  fs.mkdirSync(WB_DATA, { recursive: true });
  fs.mkdirSync(WB_GENERATED, { recursive: true });

  fs.writeFileSync(
    path.join(WB_DATA, 'sabd-wordbank.json'),
    JSON.stringify(bank, null, 2) + '\n',
  );
  fs.writeFileSync(
    path.join(WB_DATA, 'wordbank.meta.json'),
    JSON.stringify(meta, null, 2) + '\n',
  );

  const generated =
    `// GENERATED by tools/content-pipeline/src/publish.js — DO NOT EDIT BY HAND.\n` +
    `// Source: data/clean/sabd-wordbank.json  ·  wordBankVersion ${version}\n` +
    `import type { WordEntry } from '@sabd/contracts';\n\n` +
    `export const WORD_BANK_VERSION = ${JSON.stringify(version)};\n` +
    `export const WORD_BANK_GENERATED_AT = ${JSON.stringify(generatedAt)};\n\n` +
    `export const WORD_BANK: readonly WordEntry[] = ${JSON.stringify(bank, null, 2)};\n`;
  fs.writeFileSync(path.join(WB_GENERATED, 'word-bank.generated.ts'), generated);

  console.log(`Published word bank v${version}: ${bank.length} entries → packages/wordbank`);
  for (const [topic, n] of Object.entries(topicCounts)) console.log(`  ${topic}: ${n}`);
}

main();
